enhavo_page_admin_page_index:
    path: /page/index
    defaults:
        _expose: admin
        _vue:
            component: resource-index
            groups: admin
            meta:
                api: enhavo_page_admin_api_page_index
        _endpoint:
            type: admin

enhavo_page_admin_page_create:
    path: /page/create
    defaults:
        _expose: admin
        _vue:
            component: resource-input
            groups: admin
            meta:
                api: enhavo_page_admin_api_page_create
        _endpoint:
            type: admin

enhavo_page_admin_page_update:
    path: /page/update/{id}
    defaults:
        _expose: admin
        _vue:
            component: resource-input
            groups: admin
            meta:
                api: enhavo_page_admin_api_page_update
        _endpoint:
            type: admin
