cmf_routing:
    dynamic:
        controllers_by_class:
            Enhavo\Bundle\PageBundle\Entity\Page: enhavo_page.controller.page::showResourceAction

doctrine:
    orm:
        resolve_target_entities:
            Enhavo\Bundle\PageBundle\Model\PageInterface: Enhavo\Bundle\PageBundle\Entity\Page

enhavo_app:
    template_paths:
        enhavo_page:
            path: '@EnhavoPageBundle/Resources/views'
            alias: EnhavoPage
            priority: 10
    roles:
        page_index:
            role: ROLE_ENHAVO_PAGE_PAGE_INDEX
            label: page.role.label.index
            translation_domain: EnhavoPageBundle
        page_create:
            role: ROLE_ENHAVO_PAGE_PAGE_CREATE
            label: page.role.label.create
            translation_domain: EnhavoPageBundle
        page_update:
            role: ROLE_ENHAVO_PAGE_PAGE_UPDATE
            label: page.role.label.update
            translation_domain: EnhavoPageBundle
        page_delete:
            role: ROLE_ENHAVO_PAGE_PAGE_DELETE
            label: page.role.label.delete
            translation_domain: EnhavoPageBundle

enhavo_routing:
    classes:
        Enhavo\Bundle\PageBundle\Entity\Page:
            router:
                default:
                    type: routable
                view:
                    type: id
                    route: enhavo_page_page_update
                admin:
                    type: admin
                    index_route: enhavo_page_page_index
                    update_route: enhavo_page_page_update
            generators:
                prefix:
                    type: prefix
                    properties: title

enhavo_content:
    sitemap:
        collectors:
            page:
                type: publish
                repository: enhavo_page.page.repository

enhavo_navigation:
    nav_items:
        page:
            type: content
            label: page.label.page
            translation_domain: EnhavoPageBundle
            content_form: Enhavo\Bundle\PageBundle\Form\Type\PageChoiceType
            template: theme/navigation/page.html.twig

enhavo_resource:
    resources:
        enhavo_page.page:
            classes:
                model: Enhavo\Bundle\PageBundle\Entity\Page
                factory: Enhavo\Bundle\PageBundle\Factory\PageFactory
    grids:
        enhavo_page.page:
            extends: enhavo_resource.grid
            resource: enhavo_page.page
            filters:
                title:
                    type: text
                    property: title
                    label: Text
                public:
                    type: boolean
                    label: article.label.public
                    translation_domain: EnhavoArticleBundle
                    property: public
                    equals: true
                category:
                    type: taxonomy
                    label: article.label.category
                    translation_domain: EnhavoArticleBundle
                    taxonomy: article_category
                    property: categories
            columns:
                public:
                    label: article.label.public
                    translation_domain: EnhavoArticleBundle
                    property: public
                    width: 2
                    type: boolean
                    sortable: true
                    condition: "desktop"
                title:
                    type: text
                    label: article.label.title
                    translation_domain: EnhavoArticleBundle
                    property: title
                    width: 7
                    sortable: true
                publicationDate:
                    label: article.label.publicationDate
                    translation_domain: EnhavoArticleBundle
                    property: publicationDate
                    type: date
                    width: 3
                    sortable: true
                    condition: "desktop || tablet"
            batches:
                delete:
                    type: delete
                publish:
                    type: publish

    inputs:
        enhavo_article.article:
            class: Enhavo\Bundle\ResourceBundle\Input\Input
            resource: enhavo_article.article
            form: Enhavo\Bundle\ArticleBundle\Form\Type\ArticleType
            form_options:
                component_theme: admin
            tabs:
                main:
                    type: form
                    label: article.label.article
                    translation_domain: EnhavoArticleBundle
                    arrangement: |
                        link
                        title
                        teaser
                        picture
                        categories
                        tags
                        publication_date
                        published_until
                        public
                content:
                    type: content
                meta:
                    type: meta
            actions:
                save:
                    type: save
                duplicate:
                    type: duplicate
                    route: enhavo_article_admin_api_duplicate
                    permission: ROLE_ENHAVO_ARTICLE_ARTICLE_CREATE
                    enabled: 'expr:resource && resource.id'
                preview:
                    type: preview
                    route: enhavo_article_admin_article_preview
                    enabled: 'expr:resource && resource.id'
                comments:
                    type: comments
                    enabled: 'expr:resource && resource.id'